

## Get interventions


* Plot overall interventions

```{r}
interventions <- readr::read_csv("raw-data/intervention_dates.csv") %>% 
  dplyr::select(date = date_intervention, intervention, country, social_distancing) %>% 
  dplyr::mutate(date = date %>% 
                  stringr::str_replace_all("/", "-")) %>% 
  dplyr::mutate(date = as.Date(date)) %>% 
  dplyr::mutate(country = country %>% 
                  stringr::str_replace_all("south korea", "Republic of Korea") %>% 
                  stringr::str_replace_all("Usa", "United States") %>%
                  stringr::str_to_title() %>% 
                  stringr::str_replace_all("Usa", "United States") %>% 
                  stringr::str_replace_all("Republic Of Korea", "Republic of Korea")) %>% 
  dplyr::mutate(intervention = intervention %>% 
                  stringr::str_replace_all("_", " ") %>% 
                  stringr::str_to_sentence() %>%
                  stringr::str_replace("School restictions", "School restrictions") %>% 
                  stringr::str_replace("Communciation distancing", "Communication distancing")) %>% 
      dplyr::filter(!country %in% c("United States", "Thailand", "Iran")) %>% 
  tidyr::drop_na(intervention)
  

c_grepl <- purrr::partial(grepl, ignore.case = TRUE)

## Add detail to interventions
interventions <- interventions %>% 
  dplyr::mutate(intervention_cat = case_when(
    c_grepl("School", intervention) | c_grepl("University", intervention) ~ "Education",
    c_grepl("Mass gathering", intervention) ~ "Mass gathering",
    c_grepl("Travel", intervention) | c_grepl("flights", intervention) |
      c_grepl("Border", intervention) ~ "Travel", 
    c_grepl("Surveillance", intervention) | c_grepl("Contact tracing", interventions) |
      c_grepl("Government on alert", intervention) ~ "Surveillance",
    c_grepl("Quarantine", intervention) ~ "Quarantine",
    c_grepl("information", intervention) | c_grepl("awareness", intervention) |
      c_grepl("annoucement", intervention) | grepl("Communication", intervention) ~ "Information",
    c_grepl("health", intervention) | c_grepl("Enhanced care", intervention) ~ "Healthcare",
    c_grepl("work", intervention) ~ "Workplace",
    c_grepl("Lockdown", intervention) ~ "Lockdown",
    c_grepl("Isolation", intervention) ~ "Isolation",
    TRUE ~ "Other"
  ),
intervention_scale = case_when(
  c_grepl("awareness", intervention) | c_grepl("advisory", intervention) ~ "Advice",
  c_grepl("ban", intervention) ~ "Restriction",
  c_grepl("closure", intervention) ~ "Closure",
  c_grepl("surveillance", intervention) | c_grepl("isolation", intervention) |
    c_grepl("contact tracing", intervention) ~ "Public health",
  TRUE ~ "Other"
)) %>% 
  dplyr::mutate(country = country %>% 
                  factor(levels = first_cases$Country))

readr::write_csv(interventions, "output-data/interventions.csv")

summarise_ints <- function(df) {
  df %>% 
  dplyr::select(-date) %>% 
  dplyr::group_by(country, intervention) %>% 
  dplyr::slice(1) %>% 
  dplyr::ungroup() %>% 
  dplyr::count(intervention) %>% 
  tidyr::drop_na(intervention) %>% 
  dplyr::arrange(desc(n)) %>% 
  dplyr::select(Intervention = intervention, 
                `Countries that have implemented` = n)
}


summarise_interventions <- interventions %>% 
  summarise_ints()



saveRDS(summarise_interventions, "output-data/intervention_freq.rds")
```

* Summarise interventions by category

```{r}
sum_intervention_cats <- interventions %>% 
  dplyr::group_by(intervention_cat, social_distancing) %>% 
  dplyr::summarise(interventions = paste(unique(intervention), collapse = ", "))
```

* Social categories

```{r} 
sum_intervention_cats %>% 
  dplyr::filter(social_distancing %in% "yes") %>% 
  dplyr::select(-social_distancing) %>% 
  knitr::kable()
```

* Non-social categories

```{r} 
sum_intervention_cats %>% 
  dplyr::filter(social_distancing %in% "no") %>% 
  dplyr::select(-social_distancing) %>% 
  knitr::kable()
```

* Social scales

```{r} 
sum_intervention_scales <- interventions %>% 
  dplyr::group_by(intervention_scale, social_distancing) %>% 
  dplyr::summarise(interventions = paste(unique(intervention), collapse = ", "))

sum_intervention_scales %>% 
  dplyr::filter(social_distancing %in% "no") %>% 
  dplyr::select(-social_distancing) %>% 
  knitr::kable()
```

* Non-social scales

```{r}
sum_intervention_scales %>% 
  dplyr::filter(social_distancing %in% "no") %>% 
  dplyr::select(-social_distancing) %>% 
  knitr::kable()
```
* Social interventions only

```{r}
social_interventions <- interventions %>% 
  dplyr::filter(social_distancing %in% "yes") %>% 
  summarise_ints() %>% 
  dplyr::filter(`Countries that have implemented` > 1)

saveRDS(social_interventions, "output-data/social_interventions.rds")

knitr::kable(social_interventions)
```

* Non-social interventions

```{r}
non_social_interventions <- interventions %>% 
  dplyr::filter(social_distancing %in% "no") %>% 
  summarise_ints() %>% 
  dplyr::filter(`Countries that have implemented` > 1)

saveRDS(non_social_interventions, "output-data/non_social_interventions.rds")

knitr::kable(non_social_interventions)
```

* Plot social interventions

```{r social-all-time, fig.height = 12, fig.width = 12, dpi = 320}
plot_interventions <- function(intervention_type , scales = "free_y") {
  plot_df <- cases_in_countries %>% 
  dplyr::left_join(interventions %>% 
                     dplyr::filter(social_distancing %in% intervention_type),
                   by = c("date", "country")) %>% 
  dplyr::group_by(country, date) %>% 
  dplyr::mutate(cases = cases / dplyr::n())
  
  plot_df %>% 
  ggplot2::ggplot(ggplot2::aes(x = date, y = cases, col= intervention_cat)) +
  ggplot2::geom_vline(data = tidyr::drop_na(plot_df, intervention_cat),
                      aes(xintercept = date, col = intervention_cat,
                          linetype = intervention_scale), 
                      size = 1.2) +
  ggplot2::geom_col(col = NA, alpha = 0.6) +
  ggplot2::scale_fill_brewer(palette = "Dark2", na.value = "grey") +
  ggplot2::facet_wrap(~ country, scales = scales, ncol = 1) +
  cowplot::theme_cowplot() +
  labs(x = "Date", y = "Cases") +
  theme(legend.position = "bottom", legend.box="vertical") +
  labs(col = "Type", fill = NULL, linetype = "Scale")
}


plot_interventions("yes", scales = "free_y")
```

```{r social-norm-time, fig.height = 12, fig.width = 12, dpi = 320}
plot_interventions("yes", scales = "free")
```



* Plot non-social interventions

```{r non-social-all-time, fig.height = 12, fig.width = 12, dpi = 320}
plot_interventions("no", scales = "free_y")
```

```{r non-social-norm-time, fig.height = 12, fig.width = 12, dpi = 320}
plot_interventions("no", scales = "free")
```
